Python Homework (NumPy, Pandas)
Use markdown formatting for the following questions:

1. What does Pandas stand for?
Python Data Analysis

2. What are the 2 collections used in Pandas?
Series and Dataframe

3. Name 4 things Pandas can do for us.
load, manipulate, prepare, and model data

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
set the inplace parameter to True (inplace = True)

5. What is a CSV
Comma Separated Value, string values separated by commas

6. When cleaning data what values do we not like in our data?
Null or empty values



In [2]:

# 7. Please Complete this Coding Exercise:
# Import NumPy, 
#use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). 
#You can use the reshape method -- .reshape()

import numpy as np

newArr = np.arange(12).reshape((2,3,2))
print(newArr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [3]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
newArr = np.linspace(0,20, num=6)
print(newArr)

[ 0.  4.  8. 12. 16. 20.]


In [5]:
# 9. Make a Deep Copy of the above array
import copy

newArrDeepCopy = copy.deepcopy(newArr)

print(newArrDeepCopy)

[ 0.  4.  8. 12. 16. 20.]


In [11]:
# 11. Concatenate these 3 arrays into a new array named 'newArray'...
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# print(array1, array2, array3)
# print(array1.shape,array2.shape,array3.shape)
# print(array1.size,array2.size,array3.size)
# print(array1.ndim,array2.ndim,array3.ndim)

newArray = np.concatenate((array1, array2, array3), axis=0)
print(newArray)
print(newArray.shape)
print(newArray.size)
print(newArray.ndim)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
(6, 2)
12
2


In [12]:
# 12. Sort 'newArray' in order into 'sortedArray'
sortedArray = copy.deepcopy(newArray)
sortedArray.sort()
print(sortedArray)


NameError: name 'sortedArray' is not defined

In [40]:
# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray = sortedArray.reshape(2,2,3)
print(reshapedArray)


[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
(2, 2, 3)
3
12


In [54]:
# 14. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
reshapedArray = reshapedArray.reshape(4,3)

a,b,c,d = reshapedArray

print(a,"\n",b,"\n",c,"\n",d)

[16 25  2] 
 [11  4 13] 
 [ 7 81  5] 
 [ 6 11 12]


In [11]:
# 15. Combined and sort the following arrays into one called 'comboArray' ...

arrayone = np.array([10, 11, 12, 13, 14, 15, 16, 17])
arraytwo = np.array([20, 21, 22, 23, 24, 25, 26, 27])
arraythree = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((arrayone, arraytwo, arraythree), axis=0)

comboArray.sort()
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [54]:
# 16. Take 'comboArray' and perform the following slicing activities:
print(len(comboArray))


# print sec1 - the 2nd element
print(comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])

# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:14])

# print sec4 - the last 6 elements
print(comboArray[-6:])

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[:-10])

# print sec6 - from #20 every even element to the end
print(comboArray[16::2])

# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-24::5])




24
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[ 0  5 12 17 24]


In [67]:
# 20. Using Series, create a DataFrame that looks like this:

# Ingredients	Quantity	Unit
# Flour	4	cups
# Milk	1	cup
# Eggs	2	large
# Spam	1	can
# Name: Dinner, dtype: object

import numpy
import pandas as pd

ingre = pd.Series(['Flour','Milk','Eggs','Spam'], name='Ingredients')
quant = pd.Series([4,1,2,1],name = 'Quantity')
unit = pd.Series(['cups','cup','large','can'], name='Unit')
Name = pd.concat([ingre,quant, unit],axis =1)
print(Name)


  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [69]:
# 21. Take this data and create a DataFrame named studentData

studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
'Height': [5.1, 6.2, 5.1, 5.2],
'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
'Age': [21, 23, 24, 21],
'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
})
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [77]:
# 22. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
deserts = pd.Series({'deserts':["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]}, name= 'Deserts')
studentData.join(deserts)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [79]:
# 23. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ['Name', 'address'], inplace= True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball


In [80]:
# 24. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
import csv

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_andgoats.csv')

In [84]:
# 25. 
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd
import csv

vegetable = pd.DataFrame([["Carot", "Celery"], ["Orange", "Green"]],
                        columns=["Vegetable", "Color"])

vegetable.to_csv("vegetables.csv")

vegetable.sort_values(['Color', 'Vegetable'], inplace = True)

vegetable.to_csv("reorg_vegetable.csv")

Final Note:
Goal from this past week: - Expanded knowledge regarding NumPy - Understanding broadcasting - Introduction to Pandas - Knowledge and ability on how to upload documents using Pandas